### ISSUE TITLE
Release 1.1.1 is breaking change, but no major bump.

### ISSUE THREAD

**Issue by corybill** [jsreport/nodejs-client#10]
In your change from request to Axios, you removed Request's strictSSL setting but didn't replace it with Axios's rejectUnauthorized setting. This is a breaking change and necessitates a major version bump. I strongly suggest you deprecate version 1.1.1 and push your new changes to 2.0.0. Either that or leave 1.1.1 and add the rejectUnauthorized.

Thank you.

3e98b2b

**Comment by bjrmatos** [comment]
thanks, we decided to replicate the previous behaviour (stricSSL: false), so we are going to include this in 1.1.2 version

**Comment by corybill** [comment]
Thanks for the update!
