### ISSUE TITLE
Sending html template from node to jsreports server and perform action on it

### ISSUE THREAD

**Issue by Sunil-Revankar** [jsreport/nodejs-client#5]
I have created spa and running this in node server.
And l have number of template in which one the template I need to run in jsreports.
Is it possible to send template from node to jsreports and on some click operation on the report it has to communicate with the js file written in the node side.

I am using express js also with node

**Comment by Sunil-Revankar** [comment]
Please post some code to do so

**Comment by Sunil-Revankar** [comment]
This is the code where i am trying to render the template in jsreport

var jsreport = require('jsreport')({
         express: { app :reportingApp, server: server }
})

export.getReport = function(req, res){
        jsreport.init().then(function() {
           return jsreport.render({
                 template: {
                    content: fs.readFileSync(path.join("/path/sample.html"), 'utf8'),
                    engine: 'none',
                    recipe: 'html'
                 }
          }).then(function(resp){
                  resp.stream.pipe(res);
          })
       }).catch(function(e){
                console.log(e)
       })
}


export.getReport() this is called when i click on a button, but i am got getting any response.
When i debug the code, the control comes to resp.stream.pipe(res) but no redirection

**Comment by bjrmatos** [comment]
you can use something like this:

```js
var express = require('express'),
    jsreport = require('jsreport');

var app = express(),
    reportingApp = express(),
    server,
    jsreportInstance;

app.get('/', function (req, res) {
  res.send('Hello from the main application');
});

// when you GET /render you will see the html rendered by jsreport
app.get('/render', function(req, res) {
    jsreport.render({
        template: {
            content: '<h1>Test</h1>' // put your html file content here,
            engine: 'none',
            recipe: 'html'
        }
    }).then(function(resp){
        resp.stream.pipe(res);
    })
});

app.use('/reporting', reportingApp);

server = app.listen(3000);

jsreportInstance = jsreport({
  express: { app :reportingApp, server: server },
  appPath: "/reporting"
});

jsreportInstance.init().catch(function (e) {
  console.error('error initializing jsreport:', e);
});
```

**Comment by Sunil-Revankar** [comment]
Hi @bjrmatos, I tried like you said. The final result what i got is, could able to navigate to Jsreport studio but my template has not rendered over there. It shows the default sample template.

**Comment by bjrmatos** [comment]
@Sunil-Revankar hmm maybe I'm not understanding what you're trying to accomplish.

from your comments above i'm understanding the following:

- you're using jsreport inside an existing node.js express application 
- you want to send some template content (html) from your node.js application to jsreport
- when jsreport renders the html page, you want that your node.js app send a response with the html rendered by jsreport

is that correct? can you clarify or add more steps?



> The final result what i got is, could able to navigate to Jsreport studio but my template has not rendered over there. It shows the default sample template.

this is because when you send some raw template content to `jsreport.render` it doesn't store it, it just use the content to render in the same request and after that, the template that you sent is not longer available. 

if you are planning to design a template in jsreport-studio and when you are done with it, you want to use that content to render something, in that case you can use something like this:

```js
jsreport.render({
        template: {
            shortid: 'rk-kXC8Gdl',
            /* you can specify engine or recipe if you want to change what the template in studio has by default
            engine: 'none',
            recipe: 'html'
            */
        }
    }).then(function(resp){
        resp.stream.pipe(res);
    })
```

you can get the `shortid` of a template in jsreport studio using the "Link" button.

<img width="748" alt="captura de pantalla 2017-02-21 a las 9 57 45 a m" src="https://cloud.githubusercontent.com/assets/4262050/23170146/390b443e-f81c-11e6-9f7e-b96737db6436.png">

you will see a popup with an url that has the shortid in it

<img width="1068" alt="captura de pantalla 2017-02-21 a las 9 58 50 a m" src="https://cloud.githubusercontent.com/assets/4262050/23170193/5f3b568a-f81c-11e6-93df-57e566361e22.png">

please if i'm missing something, try to clarify your problem a little bit

**Comment by Sunil-Revankar** [comment]
@bjrmatos 
My requirement is other way round which imposes the first two points you mentioned above.
Here my scenario is, I am building single page application using NodeJs, which contains about 10 html pages among which 2 of them i need to use in the Jsreport, so i have already designed those templates.

In my main template i have an option to select, on click of that i need one of the template (1 of 10) to be sent to Jsreport environment to display and perform actions over there which intern commutes with my nodejs code.

As i mentioned above two of my template should be opened in jsreports which is dependent on each other, here i mean
1. I send one template to display in jsreport studio, on some action in that i need the other template to
    be displayed in the same jsreport studio. Which has to be again rendered from my SPA.

**Comment by Sunil-Revankar** [comment]
@bjrmatos If you could share any such application if you have that would be more helpful

**Comment by bjrmatos** [comment]
@Sunil-Revankar sorry but i don't have code to share for this case.

but if you can put your case in a github repository with some comments i can give it a look, this will speed up things a lot

i'm closing this because this is not an issue, but feel free to keep posting your comments

**Comment by Sunil-Revankar** [comment]
I am not able to navigate to jsreport studio with the template which i have created in the node application "Reports.html"

My code goes like this "server.js"
`var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io')(server)

var jsreport = require('jsreport-core')()
var fs = require('fs');
var path = require('path');

app.get("/", function(req, res){
   res.sendFile("index.html", {root: _dirname + "/public"});
});

app.get("/partials/:name", function(req, res){
   res.sendFile(_dirname + "/public/partials"+ req.param.name);
});

app.get("/p_Reports", function(req, res){
  jsreport.init().then(function() {
  jsreport.render({
    template: {
      content: fs.readFileSync(path.join("/public/partials/Report.html", 'utf8'),
      recipe: 'html',
      engine: 'none'
    }
  }).then(function(o) {
    o.result.pipe(res);
  }).catch(function(e) {
    console.error(e)
  })
});
});`

My application contains this Reports.html file which i need to open in the jsreport studio.
Here "public" is the folder which further contains folder "partials" and inside that Reports.html is present

My route.js is like this
`
mySPA.config(function($routeProvider, $locationProvider, $provider){
    $routeProvider
        .when('/',{
                 templateUrl: 'partials/login.html',
                 controller: 'loginController'
        })
        .when('/p_Reports',{
                 templateUrl: 'partials/Reports.html',
                 controller: 'reportsController'
        })
        .otherwise({redirectTo: "/"})
})
`

So when i run the application by commenting the ".when('/p_Reports'" block of code it navigates back to the home page (login) instead i need to land up in the jsreport studio with my custom template.
 
on performing some action i am calling this method
`
$scope.somefunction = function(name){
      $window.location.assign(name)
}
`

Here parameter "name" will have the value "p_Reports'
